[package]
name = "jailbird-core"
version = "0.1.0"
edition = "2021"

[features]
default = ["inter"]
inter = ["dep:jailbird-inter"]

[dependencies]
jailbird-choice = { path = "../choice" }
jailbird-inter = { path = "../inter", optional = true }
implicit-clone.workspace = true
