[package]
name = "jailbird-app"
version = "0.1.0"
edition = "2021"

[dependencies]
implicit-clone.workspace = true
wasm-bindgen = "0.2.93"
yew = { version = "0.21.0", features = ["csr"] }
yew-router = "0.18.0"
