[package]
name = "jailbird"
version = "0.1.0"
edition = "2021"

[features]
default = ["js"]
js = ["dep:jailbird-js"]

[dependencies]
jailbird-choice = { path = "../jailbird-choice" }
jailbird-js = { path = "../jailbird-js", optional = true }
implicit-clone.workspace = true
